image:
  file: .gitpod.Dockerfile
ports:
- port: 80
  onOpen: open-browser
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
  - command: "pip install jupyter opencv-contrib-python && mkdir /home/gitpod/.jupyter && cp jupyter_notebook_config.py /home/gitpod/.jupyter/. && jupyter notebook"